[package]
name = "kernel"
version = "0.1.0"

[lib]
name = "kernel"
path = "kernel/lib.rs"
crate-type = ["staticlib"]

[dependencies]
bitflags = "*"
spin = "0.4.4"
redox_syscall = { path = "syscall/" }
goblin = { path = "crates/goblin",default-features = false, features = ["elf32", "elf64"]}

[dev-dependencies]
arch_test = { path = "arch/test" }

[target.'cfg(target_arch = "arm")'.dependencies]
arch_arm = { path = "arch/arm" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
arch_x86_64 = { path = "arch/x86_64" }

[features]
default = []
live = []

[profile.dev]
panic = "unwind"

[profile.release]
panic = "abort"
