[package]
name = "ahcid"
version = "0.1.0"

[dependencies]
bitflags = "*"
dma = { path = "../../crates/dma/" }
io = { path = "../../crates/io/" }
spin = "*"
redox_syscall = { path = "../../syscall/" }
