[package]
name = "udpd"
version = "0.1.0"

[dependencies]
event = { path = "../../crates/event/" }
netutils = { path = "../../programs/netutils/" }
rand = { git = "https://github.com/rust-lang-nursery/rand.git" }
redox_syscall = { path = "../../syscall/" }
