[package]
name = "e1000d"
version = "0.1.0"

[dependencies]
bitflags = "*"
dma = { path = "../../crates/dma/" }
event = { path = "../../crates/event/" }
io = { path = "../../crates/io/" }
netutils = { path = "../../programs/netutils/" }
redox_syscall = { path = "../../syscall/" }
