[package]
name = "vesad"
version = "0.1.0"

[dependencies]
orbclient = "0.1"
ransid = "0.2"
rusttype = { git = "https://github.com/dylanede/rusttype.git", optional = true }
redox_syscall = { path = "../../syscall" }

[features]
default = []
