[package]
name = "orbital"
description = "The Orbital Windowing System and Compositor"
repository = "https://github.com/redox-os/orbital"
version = "0.1.0"
license-file = "LICENSE"
readme = "README.md"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[dependencies]
orbclient = "0.1"
orbimage = "0.1"
redox_syscall = { git = "https://github.com/redox-os/syscall.git" }

[replace]
"jpeg-decoder:0.1.8" = { git = "https://github.com/redox-os/jpeg-decoder.git" }
