[[drivers]]
name = "E1000 NIC"
class = 2
vendor = 32902
device = 4110
command = ["/sbin/e1000d", "$NAME", "$BAR0", "$IRQ"]

[[drivers]]
name = "RTL8168 NIC"
class = 2
vendor = 4332
device = 33128
command = ["/sbin/rtl8168d", "$NAME", "$BAR2", "$IRQ"]
