[package]
name = "ps2d"
version = "0.1.0"

[dependencies]
bitflags = "*"
event = { path = "../../crates/event/" }
io = { path = "../../crates/io/" }
orbclient = "0.1"
redox_syscall = { path = "../../syscall/" }
